version: 0.2
phases:
  pre_build:
    commands:
      - echo "Preparing for LaTeX compilation"

  build:
    commands:
      - pdflatex main.tex
      - mv main.pdf franciscoresume2023.pdf

  post_build:
    commands:
      - aws s3 cp mv franciscoresume2023.pdf s3://temporary-resume-bucket/
